name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # обновление каждый час
  workflow_dispatch:                # можно запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SPetkaa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_limit: 6
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_followup: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_lines: yes
          plugin_notable: yes
          plugin_people: yes
